site_name: Bianca workshop

nav:
  - Home: index.md
  - Practicalities: practicalities.md
  - Bianca intro (beginner): 
    - Introduction: intro.md
    - Overview: overview.md
    - Intro to NAISS-SENS and sensitive data: sens_project_short.md
    - Logging in to Bianca: login_bianca.md
    - Command-line intro: commandline.md
    - Module system: modules1.md
    - Transferring files to/from Bianca: transfer_basics.md
    - Introduction to compute nodes: slurm_intro.md
    - Summary: summary.md
    - Exercises: exercises.md
  - Intermediate workshop/hackaton: 
    - Introduction: intermediate/intro.md
    - Intro to NAISS-SENS and sensitive data: sens_project_short.md
    - Transferring files to/from Bianca: intermediate/transfer.md
    - Slurm deeper: intermediate/slurm_intermed.md
    - Software and package installation: intermediate/install.md
    - IDE:s: intermediate/ides.md
      - Jupyter: intermediate/ides.md
      - RStudio: intermediate/rstudio.md
      - VSCodium: intermediate/vscodium.md
    - Summary: intermediate/summary.md
    - Extra material:
      - extra/slurm.md
      - extra/conda.md
      - extra/pip.md
      - extra/rpackages.md
      - extra/julia.md
      - extra/containers.md
      - extra/devel.md
      - extra/jupyter.md
     
 
theme:
  name: material
  greetings: Welcome to Bianca workshop
  font:
    text: Lato
    code: JetBrains Mono

  logo: assets/logo.svg

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.footer
    - search.suggest
    - content.code.annotate
    - content.tabs.link

  custom_dir: mkdocs_uppmax/
    
extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

