site_name: Bianca workshop

nav:
  - Home: index.md
  - Practicalities: practicalities.md
  - Getting Started:
    - Overview: overview.md
    - Logging into Bianca: login_bianca.md
    - Command-line intro: 
      - linux.md
      - commandline.md
    - Module system: modules1.md
    - Transfering files to/from Bianca: transfer.md
  - NAISS-SENS and sensitive data: naiss-sens-bianca.md
  - The compute nodes and install yourself: 
    - Introduction to compute nodes: slurm-intro.md
    - Software and package installation: install.md
  - Extra material:
    - slurm.md
    - conda.md
    - pip.md
    - rpackages.md
    - julia.md
    - jupyter.md
    - containers.md
  - Exercises: exercises.md
     
 
theme:
  name: material
  greetings: Welcome to Bianca workshop
  font:
    text: Lato
    code: JetBrains Mono

  logo: assets/logo.svg

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - search.suggest
    - content.code.annotate
    - content.tabs.link

  custom_dir: mkdocs_uppmax/
    
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

