# Check that there is correct spelling in all files
name: Check spelling

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 2 * *"


jobs:
  check_spelling:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Remove folders that must allow spelling mistakes
        run: |
          rm -rf docs/evaluations
          rm -rf docs/reflections
          rm -rf docs/shared_documents

      - uses: igsekor/pyspelling-any@v0.0.2
