name: Check links

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 2 * *"


jobs:
  check_links:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Remove folders that are allowed broken links
        run: |
          rm -rf docs/sep23
          rm docs/extra/rpackages_copy.md

      # If there is a valid external link that fails,
      # add it to mlc_config.json
      - name: External links must be checked, do not allow '0' in the 'aliveStatusCodes' of mlc_config.json
        run: if [[ $(grep --regexp "[^0-9]0[^0-9]" mlc_config.json | wc --lines) == "1" ]]; then echo "FOUND"; exit 42; fi

      - name: Internal links must checked, do not allow '400' in the 'aliveStatusCodes' of mlc_config.json
        run: if [[ $(grep --regexp "[^0-9]400[^0-9]" mlc_config.json | wc --lines) == "1" ]]; then echo "FOUND"; exit 42; fi

      - uses: gaurav-nelson/github-action-markdown-link-check@v1

      # Cannot deal with emails :-/
      #- uses: lycheeverse/lychee-action@v1.2.0
      #  with:
      #    #args: --verbose --exclude-mail './**/*.md' './**/*.html'
      #    fail: true
