name: Check links

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 2 * *"


jobs:
  check_links:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Remove folders that are allowed broken links
        run: |
          rm -rf docs/sep23
          rm docs/extra/rpackages_copy.md

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: 'yes'

      # Cannot deal with emails :-/
      #- uses: lycheeverse/lychee-action@v1.2.0
      #  with:
      #    #args: --verbose --exclude-mail './**/*.md' './**/*.html'
      #    fail: true
