name: gh
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      # Install plantuml
#      - name: mkdocs build
#        uses: 'mikaelhg/mkdocs-material-plantuml@v4'
      - run: mkdocs gh-deploy --force
